# Use a imagem oficial do OpenJDK 17 como a imagem base para o backend
FROM openjdk:17-jdk-slim

# Copie o arquivo JAR do seu projeto Spring Boot para o diretório /app
COPY ./CnpjSearchApi/target/CnpjSearchApi-0.0.1-SNAPSHOT.jar /app/

# Exponha a porta 8081 para o backend Spring Boot
EXPOSE 8081

# Inicie o aplicativo Spring Boot quando o contêiner for iniciado
CMD ["java", "-jar", "/app/CnpjSearchApi-API-0.0.1-SNAPSHOT.jar"]